-- Script de création des tables pour le système de demandes eConsulat

-- Table des civilités
CREATE TABLE IF NOT EXISTS civilites (
    id SERIAL PRIMARY KEY,
    libelle VARCHAR(50) NOT NULL UNIQUE
);

-- Table des pays
CREATE TABLE IF NOT EXISTS pays (
    id SERIAL PRIMARY KEY,
    libelle VARCHAR(100) NOT NULL UNIQUE
);

-- Table des adresses
CREATE TABLE IF NOT EXISTS adresses (
    id SERIAL PRIMARY KEY,
    street_name VARCHAR(255) NOT NULL,
    street_number VARCHAR(20) NOT NULL,
    box_number VARCHAR(20),
    postal_code VARCHAR(20) NOT NULL,
    city VARCHAR(100) NOT NULL,
    country_id INTEGER NOT NULL REFERENCES pays(id)
);

-- Table des demandes
CREATE TABLE IF NOT EXISTS demandes (
    id SERIAL PRIMARY KEY,
    civilite_id INTEGER NOT NULL REFERENCES civilites(id),
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    birth_date DATE NOT NULL,
    birth_place VARCHAR(100) NOT NULL,
    birth_country_id INTEGER NOT NULL REFERENCES pays(id),
    adresse_id INTEGER NOT NULL REFERENCES adresses(id),
    father_first_name VARCHAR(100) NOT NULL,
    father_last_name VARCHAR(100) NOT NULL,
    father_birth_date DATE NOT NULL,
    father_birth_place VARCHAR(100) NOT NULL,
    father_birth_country_id INTEGER NOT NULL REFERENCES pays(id),
    mother_first_name VARCHAR(100) NOT NULL,
    mother_last_name VARCHAR(100) NOT NULL,
    mother_birth_date DATE NOT NULL,
    mother_birth_place VARCHAR(100) NOT NULL,
    mother_birth_country_id INTEGER NOT NULL REFERENCES pays(id),
    document_type VARCHAR(50) NOT NULL,
    documents_path TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id INTEGER NOT NULL REFERENCES users(id)
);

-- Index pour optimiser les performances
CREATE INDEX IF NOT EXISTS idx_demandes_user_id ON demandes(user_id);
CREATE INDEX IF NOT EXISTS idx_demandes_status ON demandes(status);
CREATE INDEX IF NOT EXISTS idx_demandes_created_at ON demandes(created_at);

-- Insertion des civilités
INSERT INTO civilites (libelle) VALUES 
    ('Monsieur'),
    ('Madame'),
    ('Mademoiselle')
ON CONFLICT (libelle) DO NOTHING;

-- Insertion des pays
INSERT INTO pays (libelle) VALUES 
    ('Guinée-Bissau'),
    ('France'),
    ('Portugal'),
    ('Sénégal'),
    ('Cap-Vert'),
    ('Mali'),
    ('Burkina Faso'),
    ('Côte d''Ivoire'),
    ('Togo'),
    ('Bénin'),
    ('Niger'),
    ('Tchad'),
    ('Cameroun'),
    ('Gabon'),
    ('Congo'),
    ('République démocratique du Congo'),
    ('République centrafricaine'),
    ('Tchad'),
    ('Soudan'),
    ('Éthiopie'),
    ('Somalie'),
    ('Kenya'),
    ('Tanzanie'),
    ('Ouganda'),
    ('Rwanda'),
    ('Burundi'),
    ('Angola'),
    ('Zambie'),
    ('Zimbabwe'),
    ('Mozambique'),
    ('Madagascar'),
    ('Maurice'),
    ('Seychelles'),
    ('Comores'),
    ('Djibouti'),
    ('Érythrée'),
    ('Algérie'),
    ('Maroc'),
    ('Tunisie'),
    ('Libye'),
    ('Égypte'),
    ('Soudan du Sud'),
    ('Équateur'),
    ('Guinée'),
    ('Guinée équatoriale'),
    ('São Tomé-et-Principe'),
    ('Canada'),
    ('États-Unis'),
    ('Brésil'),
    ('Argentine'),
    ('Chili'),
    ('Uruguay'),
    ('Paraguay'),
    ('Bolivie'),
    ('Pérou'),
    ('Équateur'),
    ('Colombie'),
    ('Venezuela'),
    ('Guyana'),
    ('Suriname'),
    ('Guyane française'),
    ('Royaume-Uni'),
    ('Allemagne'),
    ('Italie'),
    ('Espagne'),
    ('Pays-Bas'),
    ('Belgique'),
    ('Suisse'),
    ('Autriche'),
    ('Suède'),
    ('Norvège'),
    ('Danemark'),
    ('Finlande'),
    ('Pologne'),
    ('République tchèque'),
    ('Slovaquie'),
    ('Hongrie'),
    ('Roumanie'),
    ('Bulgarie'),
    ('Grèce'),
    ('Chypre'),
    ('Malte'),
    ('Slovénie'),
    ('Croatie'),
    ('Bosnie-Herzégovine'),
    ('Serbie'),
    ('Monténégro'),
    ('Kosovo'),
    ('Macédoine du Nord'),
    ('Albanie'),
    ('Moldavie'),
    ('Ukraine'),
    ('Biélorussie'),
    ('Lituanie'),
    ('Lettonie'),
    ('Estonie'),
    ('Russie'),
    ('Turquie'),
    ('Géorgie'),
    ('Arménie'),
    ('Azerbaïdjan'),
    ('Iran'),
    ('Irak'),
    ('Syrie'),
    ('Liban'),
    ('Jordanie'),
    ('Israël'),
    ('Palestine'),
    ('Arabie saoudite'),
    ('Yémen'),
    ('Oman'),
    ('Émirats arabes unis'),
    ('Qatar'),
    ('Bahreïn'),
    ('Koweït'),
    ('Afghanistan'),
    ('Pakistan'),
    ('Inde'),
    ('Népal'),
    ('Bhoutan'),
    ('Bangladesh'),
    ('Sri Lanka'),
    ('Maldives'),
    ('Chine'),
    ('Mongolie'),
    ('Corée du Nord'),
    ('Corée du Sud'),
    ('Japon'),
    ('Taïwan'),
    ('Vietnam'),
    ('Laos'),
    ('Cambodge'),
    ('Thaïlande'),
    ('Myanmar'),
    ('Malaisie'),
    ('Singapour'),
    ('Indonésie'),
    ('Philippines'),
    ('Brunei'),
    ('Timor oriental'),
    ('Papouasie-Nouvelle-Guinée'),
    ('Fidji'),
    ('Vanuatu'),
    ('Nouvelle-Calédonie'),
    ('Australie'),
    ('Nouvelle-Zélande')
ON CONFLICT (libelle) DO NOTHING; 